export * from './capsule.type';
export * from './faq.type';
export * from './photo.type';
export * from './review.type';
export * from './user.type';
export * from './client.type';
export * from './stylist.type';
export * from './order.type';
export * from './payment.type';